set(SOURCES_MICROPROFILE

    #${CMAKE_CURRENT_LIST_DIR}/
    ${CMAKE_CURRENT_LIST_DIR}/microprofile.cpp
)
set(HEADERS_MICROPROFILE

    #${CMAKE_CURRENT_LIST_DIR}/
    ${CMAKE_CURRENT_LIST_DIR}/microprofile.h
    ${CMAKE_CURRENT_LIST_DIR}/microprofile_html.h
)